/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CatalogRouteImport } from './routes/catalog'
import { Route as SuccessRouteImport } from './routes/success'
import { Route as ApiCartRouteImport } from './routes/api/cart'
import { Route as ApiSearchRouteImport } from './routes/api/search'
import { Route as ApiShippingCalcRouteImport } from './routes/api/shipping-calc'
import { Route as ApiCheckoutSubmitRouteImport } from './routes/api/checkout/submit'
import { Route as ApiDadataCityRouteImport } from './routes/api/dadata/city'
import { Route as ApiParserUploadRouteImport } from './routes/api/parser/upload'
import { Route as ApiVisionIdentifyRouteImport } from './routes/api/vision/identify'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogRoute = CatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const SuccessRoute = SuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCartRoute = ApiCartRouteImport.update({
  id: '/api/cart',
  path: '/api/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSearchRoute = ApiSearchRouteImport.update({
  id: '/api/search',
  path: '/api/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiShippingCalcRoute = ApiShippingCalcRouteImport.update({
  id: '/api/shipping-calc',
  path: '/api/shipping-calc',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCheckoutSubmitRoute = ApiCheckoutSubmitRouteImport.update({
  id: '/api/checkout/submit',
  path: '/api/checkout/submit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDadataCityRoute = ApiDadataCityRouteImport.update({
  id: '/api/dadata/city',
  path: '/api/dadata/city',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiParserUploadRoute = ApiParserUploadRouteImport.update({
  id: '/api/parser/upload',
  path: '/api/parser/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVisionIdentifyRoute = ApiVisionIdentifyRouteImport.update({
  id: '/api/vision/identify',
  path: '/api/vision/identify',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/catalog': typeof CatalogRoute
  '/success': typeof SuccessRoute
  '/api/cart': typeof ApiCartRoute
  '/api/search': typeof ApiSearchRoute
  '/api/shipping-calc': typeof ApiShippingCalcRoute
  '/api/checkout/submit': typeof ApiCheckoutSubmitRoute
  '/api/dadata/city': typeof ApiDadataCityRoute
  '/api/parser/upload': typeof ApiParserUploadRoute
  '/api/vision/identify': typeof ApiVisionIdentifyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/catalog': typeof CatalogRoute
  '/success': typeof SuccessRoute
  '/api/cart': typeof ApiCartRoute
  '/api/search': typeof ApiSearchRoute
  '/api/shipping-calc': typeof ApiShippingCalcRoute
  '/api/checkout/submit': typeof ApiCheckoutSubmitRoute
  '/api/dadata/city': typeof ApiDadataCityRoute
  '/api/parser/upload': typeof ApiParserUploadRoute
  '/api/vision/identify': typeof ApiVisionIdentifyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/catalog': typeof CatalogRoute
  '/success': typeof SuccessRoute
  '/api/cart': typeof ApiCartRoute
  '/api/search': typeof ApiSearchRoute
  '/api/shipping-calc': typeof ApiShippingCalcRoute
  '/api/checkout/submit': typeof ApiCheckoutSubmitRoute
  '/api/dadata/city': typeof ApiDadataCityRoute
  '/api/parser/upload': typeof ApiParserUploadRoute
  '/api/vision/identify': typeof ApiVisionIdentifyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cart'
    | '/catalog'
    | '/success'
    | '/api/cart'
    | '/api/search'
    | '/api/shipping-calc'
    | '/api/checkout/submit'
    | '/api/dadata/city'
    | '/api/parser/upload'
    | '/api/vision/identify'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cart'
    | '/catalog'
    | '/success'
    | '/api/cart'
    | '/api/search'
    | '/api/shipping-calc'
    | '/api/checkout/submit'
    | '/api/dadata/city'
    | '/api/parser/upload'
    | '/api/vision/identify'
  id:
    | '__root__'
    | '/'
    | '/cart'
    | '/catalog'
    | '/success'
    | '/api/cart'
    | '/api/search'
    | '/api/shipping-calc'
    | '/api/checkout/submit'
    | '/api/dadata/city'
    | '/api/parser/upload'
    | '/api/vision/identify'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CartRoute: typeof CartRoute
  CatalogRoute: typeof CatalogRoute
  SuccessRoute: typeof SuccessRoute
  ApiCartRoute: typeof ApiCartRoute
  ApiSearchRoute: typeof ApiSearchRoute
  ApiShippingCalcRoute: typeof ApiShippingCalcRoute
  ApiCheckoutSubmitRoute: typeof ApiCheckoutSubmitRoute
  ApiDadataCityRoute: typeof ApiDadataCityRoute
  ApiParserUploadRoute: typeof ApiParserUploadRoute
  ApiVisionIdentifyRoute: typeof ApiVisionIdentifyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog': {
      id: '/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof CatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/success': {
      id: '/success'
      path: '/success'
      fullPath: '/success'
      preLoaderRoute: typeof SuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cart': {
      id: '/api/cart'
      path: '/api/cart'
      fullPath: '/api/cart'
      preLoaderRoute: typeof ApiCartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/search': {
      id: '/api/search'
      path: '/api/search'
      fullPath: '/api/search'
      preLoaderRoute: typeof ApiSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/shipping-calc': {
      id: '/api/shipping-calc'
      path: '/api/shipping-calc'
      fullPath: '/api/shipping-calc'
      preLoaderRoute: typeof ApiShippingCalcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/checkout/submit': {
      id: '/api/checkout/submit'
      path: '/api/checkout/submit'
      fullPath: '/api/checkout/submit'
      preLoaderRoute: typeof ApiCheckoutSubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dadata/city': {
      id: '/api/dadata/city'
      path: '/api/dadata/city'
      fullPath: '/api/dadata/city'
      preLoaderRoute: typeof ApiDadataCityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/parser/upload': {
      id: '/api/parser/upload'
      path: '/api/parser/upload'
      fullPath: '/api/parser/upload'
      preLoaderRoute: typeof ApiParserUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/vision/identify': {
      id: '/api/vision/identify'
      path: '/api/vision/identify'
      fullPath: '/api/vision/identify'
      preLoaderRoute: typeof ApiVisionIdentifyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CartRoute: CartRoute,
  CatalogRoute: CatalogRoute,
  SuccessRoute: SuccessRoute,
  ApiCartRoute: ApiCartRoute,
  ApiSearchRoute: ApiSearchRoute,
  ApiShippingCalcRoute: ApiShippingCalcRoute,
  ApiCheckoutSubmitRoute: ApiCheckoutSubmitRoute,
  ApiDadataCityRoute: ApiDadataCityRoute,
  ApiParserUploadRoute: ApiParserUploadRoute,
  ApiVisionIdentifyRoute: ApiVisionIdentifyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
