/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CatalogRouteImport } from './routes/catalog'
import { Route as ApiShippingCalcRouteImport } from './routes/api/shipping-calc'
import { Route as ApiLogisticsQuoteRouteImport } from './routes/api/logistics/quote'
import { Route as ApiParserUploadRouteImport } from './routes/api/parser/upload'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogRoute = CatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiShippingCalcRoute = ApiShippingCalcRouteImport.update({
  id: '/api/shipping-calc',
  path: '/api/shipping-calc',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLogisticsQuoteRoute = ApiLogisticsQuoteRouteImport.update({
  id: '/api/logistics/quote',
  path: '/api/logistics/quote',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiParserUploadRoute = ApiParserUploadRouteImport.update({
  id: '/api/parser/upload',
  path: '/api/parser/upload',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/catalog': typeof CatalogRoute
  '/api/shipping-calc': typeof ApiShippingCalcRoute
  '/api/logistics/quote': typeof ApiLogisticsQuoteRoute
  '/api/parser/upload': typeof ApiParserUploadRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/catalog': typeof CatalogRoute
  '/api/shipping-calc': typeof ApiShippingCalcRoute
  '/api/logistics/quote': typeof ApiLogisticsQuoteRoute
  '/api/parser/upload': typeof ApiParserUploadRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/catalog': typeof CatalogRoute
  '/api/shipping-calc': typeof ApiShippingCalcRoute
  '/api/logistics/quote': typeof ApiLogisticsQuoteRoute
  '/api/parser/upload': typeof ApiParserUploadRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cart'
    | '/catalog'
    | '/api/shipping-calc'
    | '/api/logistics/quote'
    | '/api/parser/upload'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cart'
    | '/catalog'
    | '/api/shipping-calc'
    | '/api/logistics/quote'
    | '/api/parser/upload'
  id:
    | '__root__'
    | '/'
    | '/cart'
    | '/catalog'
    | '/api/shipping-calc'
    | '/api/logistics/quote'
    | '/api/parser/upload'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CartRoute: typeof CartRoute
  CatalogRoute: typeof CatalogRoute
  ApiShippingCalcRoute: typeof ApiShippingCalcRoute
  ApiLogisticsQuoteRoute: typeof ApiLogisticsQuoteRoute
  ApiParserUploadRoute: typeof ApiParserUploadRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog': {
      id: '/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof CatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/shipping-calc': {
      id: '/api/shipping-calc'
      path: '/api/shipping-calc'
      fullPath: '/api/shipping-calc'
      preLoaderRoute: typeof ApiShippingCalcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/logistics/quote': {
      id: '/api/logistics/quote'
      path: '/api/logistics/quote'
      fullPath: '/api/logistics/quote'
      preLoaderRoute: typeof ApiLogisticsQuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/parser/upload': {
      id: '/api/parser/upload'
      path: '/api/parser/upload'
      fullPath: '/api/parser/upload'
      preLoaderRoute: typeof ApiParserUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CartRoute: CartRoute,
  CatalogRoute: CatalogRoute,
  ApiShippingCalcRoute: ApiShippingCalcRoute,
  ApiLogisticsQuoteRoute: ApiLogisticsQuoteRoute,
  ApiParserUploadRoute: ApiParserUploadRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
